name = "Optical_Drift_Effects"
uuid = "52dcf817-01fa-4c27-b0ac-529e854531ff"
version = "0.1.0"
authors = ["Christopher Harvey-Hawes"]

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Contour = "0.6.3"
ForwardDiff = "0.10"
Plots = "1.41.6"
SpecialFunctions = "2.7.1"
StaticArrays = "1"
julia = "1.12"
